name: campuslf
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.0
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  provider: ^6.1.2
  intl: ^0.19.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  shared_preferences: ^2.2.3
  firebase_database: ^11.0.2
  uuid: ^4.4.0
  path_provider: ^2.1.3
  async: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "web/icons/Icon-512.png"
  adaptive_icon_background: "#667eea"
  adaptive_icon_foreground: "web/icons/Icon-192.png"
  min_sdk_android: 21